/*
 * CogniRunner - AI-powered workflow validation for Jira
 * Copyright (C) 2025 LeanZero
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * GENERATED — DO NOT EDIT.
 *
 * Section and pack TITLES only — the module the UI bundles import.
 *
 * id -> title, nothing else. The full index (tags, audiences, byte counts, provenance)
 * is src/shared/knowledge-index.js and belongs to the backend and the Knowledge tab;
 * importing THAT from a frontend ships 136 KB to render a label (F-573).
 *
 * Produced by scripts/bake-knowledge.mjs from the allow-list in knowledge/sources.json.
 * Edit the SOURCE and re-bake; an edit here is overwritten the next time anyone runs the
 * pipeline, and it would not carry the provenance or the leak scan that make this file
 * safe to ship. Dependency-free on purpose: this bundles into the Forge backend and the
 * webpack builds alike.
 *
 * The human-review artefact for this content is knowledge/MANIFEST.md.
 */

/** Content fingerprint of the baked corpus — the same value src/shared/knowledge-index.js pins. */
export const KNOWLEDGE_TITLES_VERSION = "4daff10f6d5d5c5b";

export const KNOWLEDGE_PACK_TITLES = {
  "administrator-practice": "Administrator practice",
  "automation-semantics": "Automation semantics",
  "cognirunner-sandbox-traps": "CogniRunner sandbox traps",
  "confluence-rest-correctness": "Confluence REST correctness",
  "forge-app-builder": "Forge app builder",
  "forge-platform-facts": "Forge platform facts",
  "jira-rest-correctness": "Jira REST correctness",
  "jsm-correctness": "Jira Service Management correctness",
  "voice-rules": "Voice rules"
};

export const KNOWLEDGE_TITLES = {
  "administrator-practice/administrator-practice/6d0d454c/administrator-practice-1": "Administrator practice",
  "administrator-practice/administrator-practice/6d0d454c/burstiness-length-and-the-shape-of-outward-text-8": "Burstiness, length and the shape of outward text",
  "administrator-practice/administrator-practice/6d0d454c/guard-discipline-and-dead-enforcement-5": "Guard discipline and dead enforcement",
  "administrator-practice/administrator-practice/6d0d454c/platform-cap-guards-6": "Platform-cap guards",
  "administrator-practice/administrator-practice/6d0d454c/proven-negatives-and-what-an-endpoint-quietly-excludes-2": "Proven negatives and what an endpoint quietly excludes",
  "administrator-practice/administrator-practice/6d0d454c/speaking-versus-changing-and-the-approval-axis-3": "Speaking versus changing, and the approval axis",
  "administrator-practice/administrator-practice/6d0d454c/the-effects-ledger-4": "The effects ledger",
  "administrator-practice/administrator-practice/6d0d454c/the-operating-loop-9": "The operating loop",
  "administrator-practice/administrator-practice/6d0d454c/unattended-operation-7": "Unattended operation",
  "automation-semantics/automation-semantics/9d8eb604/automation-semantics-1": "Automation semantics",
  "automation-semantics/automation-semantics/9d8eb604/rule-limits-worth-designing-around-3": "Rule limits worth designing around",
  "automation-semantics/automation-semantics/9d8eb604/service-management-over-rest-workflows-fields-and-verificati-4": "Service management over REST: workflows, fields and verification",
  "automation-semantics/automation-semantics/9d8eb604/smart-values-what-renders-and-what-silently-renders-empty-2": "Smart values: what renders and what silently renders empty",
  "cognirunner-sandbox-traps/cognirunner-gotchas/4870432a/12-two-agents-one-working-tree-4": "12. Two agents, one working tree",
  "cognirunner-sandbox-traps/cognirunner-gotchas/4870432a/17-an-assets-object-field-silently-stores-nothing-until-conf-5": "17. An Assets object field silently stores nothing until configured in the UI",
  "cognirunner-sandbox-traps/cognirunner-gotchas/4870432a/4-a-silent-wrong-issue-write-hides-behind-a-type-check-that--2": "4. A silent wrong-issue WRITE hides behind a type check that looks defensive",
  "cognirunner-sandbox-traps/cognirunner-gotchas/4870432a/7-forge-logs-cannot-be-relied-on-for-a-specific-window-3": "7. forge logs cannot be relied on for a specific window",
  "cognirunner-sandbox-traps/cognirunner-gotchas/4870432a/gotchas-traps-each-with-its-receipt-1": "GOTCHAS — traps, each with its receipt",
  "confluence-rest-correctness/confluence-api/7042ac24/email-address-needs-a-scope-3": "Email address needs a scope",
  "confluence-rest-correctness/confluence-api/7042ac24/forge-development-gotchas-confluence-1": "Forge Development Gotchas (Confluence)",
  "confluence-rest-correctness/confluence-api/7042ac24/large-page-content-in-custom-ui-2": "Large Page Content in Custom UI",
  "confluence-rest-correctness/confluence-api/95b3f442/next-steps-6": "Next Steps",
  "confluence-rest-correctness/confluence-api/95b3f442/pattern-2-display-sync-status-on-page-2": "Pattern 2: Display Sync Status on Page",
  "confluence-rest-correctness/confluence-api/95b3f442/pattern-3-space-wide-configuration-with-per-page-overrides-3": "Pattern 3: Space-Wide Configuration with Per-Page Overrides",
  "confluence-rest-correctness/confluence-api/95b3f442/pattern-4-reconciliation-scheduler-for-missed-webhooks-4": "Pattern 4: Reconciliation Scheduler for Missed Webhooks",
  "confluence-rest-correctness/confluence-api/95b3f442/pattern-5-handle-rate-limits-with-exponential-backoff-5": "Pattern 5: Handle Rate Limits with Exponential Backoff",
  "confluence-rest-correctness/confluence-api/95b3f442/problem-patterns-common-confluence-forge-solutions-1": "Problem Patterns: Common Confluence Forge Solutions",
  "confluence-rest-correctness/confluence-forge/0a6ac900/1-manifest-manifest-yml-3": "1. Manifest (manifest.yml)",
  "confluence-rest-correctness/confluence-forge/0a6ac900/3-resources-4": "3. Resources",
  "confluence-rest-correctness/confluence-forge/0a6ac900/architecture-overview-2": "Architecture Overview",
  "confluence-rest-correctness/confluence-forge/0a6ac900/core-concepts-forge-for-confluence-cloud-1": "Core Concepts: Forge for Confluence Cloud",
  "confluence-rest-correctness/confluence-forge/0a6ac900/event-types-for-triggers-part-1-7": "Event Types for Triggers (part 1)",
  "confluence-rest-correctness/confluence-forge/0a6ac900/event-types-for-triggers-part-2-8": "Event Types for Triggers (part 2)",
  "confluence-rest-correctness/confluence-forge/0a6ac900/permissions-scopes-6": "Permissions & Scopes",
  "confluence-rest-correctness/confluence-forge/0a6ac900/the-resolver-pattern-backend-api-calls-5": "The Resolver Pattern (Backend API Calls)",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/1-capsule-style-resolver-registration-2": "1. Capsule-style resolver registration",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/10-dual-strategy-asuser-asapp-fallback-7": "10. Dual-strategy asUser → asApp fallback",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/12-resolver-middleware-withmigrations-wrapper-8": "12. Resolver middleware (withMigrations) wrapper",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/14-email-without-a-third-party-provider-jira-issue-notify-tr-9": "14. Email without a third-party provider (Jira issue notify trick)",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/16-in-isolate-config-cache-for-high-frequency-handlers-10": "16. In-isolate config cache for high-frequency handlers",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/18-dual-index-ts-handler-resolution-typescript-forge-apps-11": "18. Dual index.ts handler resolution (TypeScript Forge apps)",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/3-content-property-version-handling-3": "3. Content-property version handling",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/5-app-account-id-loop-prevention-4": "5. App-account-id loop prevention",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/7-cursor-paginated-space-scan-from-a-queue-5": "7. Cursor-paginated space scan from a queue",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/8-three-level-confluence-authorization-6": "8. Three-level Confluence authorization",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/production-patterns-confluence-1": "Production Patterns (Confluence)",
  "confluence-rest-correctness/confluence-forge/42e5ae3d/see-also-12": "See also",
  "confluence-rest-correctness/confluence-forge/6e1199f9/architecture-patterns-that-survived-production-part-1-5": "Architecture patterns that survived production (part 1)",
  "confluence-rest-correctness/confluence-forge/6e1199f9/architecture-patterns-that-survived-production-part-2-6": "Architecture patterns that survived production (part 2)",
  "confluence-rest-correctness/confluence-forge/6e1199f9/points-based-rate-limiting-enforced-2026-03-02-surviving-tie-1": "Points-based rate limiting (enforced 2026-03-02) — surviving Tier 1",
  "confluence-rest-correctness/confluence-forge/6e1199f9/pool-scope-what-is-actually-documented-4": "Pool scope: what is actually documented",
  "confluence-rest-correctness/confluence-forge/6e1199f9/the-space-permissions-trap-measured-and-it-will-bite-you-3": "The space-permissions trap (measured, and it will bite you)",
  "confluence-rest-correctness/confluence-forge/6e1199f9/what-actually-counts-the-cheapest-optimisation-there-is-2": "What actually counts (the cheapest optimisation there is)",
  "confluence-rest-correctness/confluence-forge/cf6b16f6/adf-and-storage-format-confluence-body-formats-1": "ADF and Storage Format — Confluence body formats",
  "confluence-rest-correctness/confluence-forge/cf6b16f6/building-common-adf-nodes-2": "Building common ADF nodes",
  "confluence-rest-correctness/confluence-forge/cf6b16f6/canonical-adf-hashing-tamper-detection-3": "Canonical ADF hashing (tamper detection)",
  "confluence-rest-correctness/confluence-forge/cf6b16f6/mixing-v1-and-v2-endpoints-4": "Mixing v1 and v2 endpoints",
  "confluence-rest-correctness/confluence-forge/db2a8d8f/4-permission-check-in-functions-3": "4. Permission Check in Functions",
  "confluence-rest-correctness/confluence-forge/db2a8d8f/blog-post-events-2": "Blog Post Events",
  "confluence-rest-correctness/confluence-forge/db2a8d8f/confluence-forge-permissions-oauth-scopes-1": "Confluence Forge Permissions & OAuth Scopes",
  "confluence-rest-correctness/confluence-forge/f719b57e/kvs-key-schemes-2": "KVS key schemes",
  "confluence-rest-correctness/confluence-forge/f719b57e/macros-section-sealing-1": "Macros & Section Sealing",
  "confluence-rest-correctness/confluence-forge/f719b57e/realm-space-seal-index-via-prefix-query-4": "Realm/space seal index via prefix query",
  "confluence-rest-correctness/confluence-forge/f719b57e/three-way-seal-lifecycle-3": "Three-way seal lifecycle",
  "forge-app-builder/forge-security-review/060270ba/2-the-unvalidated-zero-a-scanner-with-no-rules-looks-exactly-2": "2. The unvalidated zero — a scanner with no rules looks exactly like clean code",
  "forge-app-builder/forge-security-review/060270ba/5-the-sandbox-is-a-blast-radius-argument-not-an-absolution-3": "5. The sandbox is a blast-radius argument, not an absolution",
  "forge-app-builder/forge-security-review/060270ba/8-vendor-attestation-dressed-up-as-proof-4": "8. Vendor attestation dressed up as proof",
  "forge-app-builder/forge-security-review/060270ba/the-traps-read-before-reporting-anything-1": "The traps — read before reporting anything",
  "forge-app-builder/forge-security-review/9babab17/forge-app-security-review-run-the-reports-then-write-one-tha-1": "Forge app security review — run the reports, then write one that holds up",
  "forge-app-builder/forge-security-review/9babab17/standing-directive-keep-this-current-3": "Standing directive: keep this current",
  "forge-app-builder/forge-security-review/9babab17/the-method-2": "The method",
  "forge-app-builder/forge-security-review/da20948d/2-decompression-bombs-on-the-untrusted-file-path-2": "2. Decompression bombs on the untrusted-file path",
  "forge-app-builder/forge-security-review/da20948d/6-scope-over-provisioning-3": "6. Scope over-provisioning",
  "forge-app-builder/forge-security-review/da20948d/a-turn-boundary-is-not-consent-4": "A turn boundary is not consent",
  "forge-app-builder/forge-security-review/da20948d/what-sast-and-sca-structurally-cannot-see-in-a-forge-app-1": "What SAST and SCA structurally cannot see in a Forge app",
  "forge-app-builder/jira-forge/010c4865/a-custom-ui-resource-is-a-directory-4": "A Custom UI resource is a DIRECTORY",
  "forge-app-builder/jira-forge/010c4865/faas-limits-cost-reference-1": "FaaS Limits & Cost Reference",
  "forge-app-builder/jira-forge/010c4865/queue-forge-events-limits-2": "Queue (@forge/events) limits",
  "forge-app-builder/jira-forge/010c4865/when-you-hit-a-wall-3": "When you hit a wall",
  "forge-app-builder/jira-forge/636106f9/2-heartbeat-self-heal-cap-4": "2. Heartbeat + self-heal cap",
  "forge-app-builder/jira-forge/636106f9/2-hourly-lazy-refresh-scheduled-trigger-3": "2. Hourly lazy-refresh scheduled trigger",
  "forge-app-builder/jira-forge/636106f9/async-events-queues-forge-events-1": "Async Events & Queues (`@forge/events`)",
  "forge-app-builder/jira-forge/636106f9/consumer-handler-signature-2": "Consumer: handler signature",
  "forge-app-builder/jira-forge/636106f9/see-also-5": "See also",
  "forge-app-builder/jira-forge/790cea09/core-forge-concepts-1": "Core Forge Concepts",
  "forge-app-builder/jira-forge/790cea09/function-2": "Function",
  "forge-app-builder/jira-forge/790cea09/scheduled-triggers-3": "Scheduled Triggers",
  "forge-app-builder/jira-forge/7d4704eb/1-define-functions-in-backend-2": "1. Define Functions in Backend",
  "forge-app-builder/jira-forge/7d4704eb/3-performance-optimization-7": "3. Performance Optimization",
  "forge-app-builder/jira-forge/7d4704eb/caching-5": "Caching",
  "forge-app-builder/jira-forge/7d4704eb/forge-resolver-patterns-1": "Forge Resolver Patterns",
  "forge-app-builder/jira-forge/7d4704eb/input-payload-structure-3": "Input Payload Structure",
  "forge-app-builder/jira-forge/7d4704eb/input-validation-4": "Input Validation",
  "forge-app-builder/jira-forge/7d4704eb/keep-the-one-shot-path-8": "Keep the one-shot path",
  "forge-app-builder/jira-forge/7d4704eb/transaction-management-6": "Transaction Management",
  "forge-app-builder/jira-forge/80f86740/agentic-validation-validators-only-4": "Agentic validation (validators only)",
  "forge-app-builder/jira-forge/80f86740/field-editability-pre-flight-for-semantic-post-functions-5": "Field editability pre-flight for semantic post-functions",
  "forge-app-builder/jira-forge/80f86740/one-resolver-separately-exported-runtime-functions-2": "One resolver, separately-exported runtime functions",
  "forge-app-builder/jira-forge/80f86740/registry-cache-30-s-warm-container-staleness-3": "Registry cache: ~30 s warm-container staleness",
  "forge-app-builder/jira-forge/80f86740/workflow-modules-deep-dive-1": "Workflow Modules — Deep Dive",
  "forge-app-builder/jira-forge/b96476d2/1-kvs-sharding-for-100-item-collections-2": "1. KVS sharding for >100-item collections",
  "forge-app-builder/jira-forge/b96476d2/10-workflow-injection-programmatic-rule-add-9": "10. Workflow injection (programmatic rule add)",
  "forge-app-builder/jira-forge/b96476d2/11-hourly-lazy-refresh-scheduled-trigger-10": "11. Hourly lazy-refresh scheduled trigger",
  "forge-app-builder/jira-forge/b96476d2/13-concurrency-deep-dive-stale-draft-invalidation-cleanup-11": "13. Concurrency deep-dive: stale-draft invalidation + cleanup",
  "forge-app-builder/jira-forge/b96476d2/14-chunked-write-back-with-a-post-write-verify-step-12": "14. Chunked write-back with a post-write VERIFY step",
  "forge-app-builder/jira-forge/b96476d2/16-layered-config-loader-loaded-fresh-per-invocation-13": "16. Layered config loader, loaded fresh per invocation",
  "forge-app-builder/jira-forge/b96476d2/18-issue-link-inward-outward-semantics-14": "18. Issue-link inward/outward semantics",
  "forge-app-builder/jira-forge/b96476d2/2-two-pass-dependency-filtering-3": "2. Two-pass dependency filtering",
  "forge-app-builder/jira-forge/b96476d2/20-field-screen-warning-preflight-15": "20. Field-screen warning preflight",
  "forge-app-builder/jira-forge/b96476d2/21-materialising-a-generated-hierarchy-into-jira-resumably-16": "21. Materialising a generated hierarchy into Jira, resumably",
  "forge-app-builder/jira-forge/b96476d2/4-chunked-write-back-with-lock-refresh-4": "4. Chunked write-back with lock refresh",
  "forge-app-builder/jira-forge/b96476d2/5-drafts-write-locks-for-multi-user-concurrency-5": "5. Drafts + write-locks for multi-user concurrency",
  "forge-app-builder/jira-forge/b96476d2/6-capability-token-web-triggers-6": "6. Capability-token web triggers",
  "forge-app-builder/jira-forge/b96476d2/7-async-queue-offload-for-25-s-work-7": "7. Async-queue offload for >25 s work",
  "forge-app-builder/jira-forge/b96476d2/9-fail-open-workflow-validators-8": "9. Fail-open workflow validators",
  "forge-app-builder/jira-forge/b96476d2/hash-a-canonical-blast-radius-not-the-raw-arguments-18": "Hash a canonical BLAST RADIUS, not the raw arguments",
  "forge-app-builder/jira-forge/b96476d2/production-patterns-1": "Production Patterns",
  "forge-app-builder/jira-forge/b96476d2/see-also-17": "See also",
  "forge-app-builder/jira-forge/e23d057d/byok-multi-provider-adapter-3": "BYOK multi-provider adapter",
  "forge-app-builder/jira-forge/e23d057d/forge-ai-llm-integration-1": "Forge AI & LLM Integration",
  "forge-app-builder/jira-forge/e23d057d/hosted-vs-byok-how-to-choose-4": "Hosted vs BYOK — how to choose",
  "forge-app-builder/jira-forge/e23d057d/model-ids-use-these-verbatim-from-the-claude-api-skill-2": "Model ids (use these verbatim — from the claude-api skill)",
  "forge-app-builder/jira-forge/e23d057d/output-ceiling-is-not-32k-it-is-the-model-s-own-5": "Output ceiling is NOT 32k — it is the model's own",
  "forge-app-builder/jira-forge/e23d057d/output-length-is-the-ceiling-for-structured-generation-not-c-6": "OUTPUT LENGTH is the ceiling for structured generation, not context",
  "forge-app-builder/jira-forge/e23d057d/write-progress-to-the-job-row-the-poller-is-already-reading--7": "Write progress to the job row; the poller is already reading it",
  "forge-platform-facts/jira-forge/5b7cf75d/5-use-etags-for-conditional-requests-5": "5. Use ETags for Conditional Requests",
  "forge-platform-facts/jira-forge/5b7cf75d/complete-implementation-with-quota-tracking-part-1-3": "Complete Implementation with Quota Tracking (part 1)",
  "forge-platform-facts/jira-forge/5b7cf75d/complete-implementation-with-quota-tracking-part-2-4": "Complete Implementation with Quota Tracking (part 2)",
  "forge-platform-facts/jira-forge/5b7cf75d/detect-all-three-limit-types-2": "Detect All Three Limit Types",
  "forge-platform-facts/jira-forge/5b7cf75d/if-you-build-a-self-meter-it-is-not-capture-only-if-anything-8": "If you build a self-meter, it is not \"capture-only\" if anything reads it",
  "forge-platform-facts/jira-forge/5b7cf75d/jira-s-identity-class-is-wider-than-confluence-s-7": "Jira's identity class is wider than Confluence's",
  "forge-platform-facts/jira-forge/5b7cf75d/patterns-proven-under-the-confluence-points-quota-that-trans-6": "Patterns proven under the Confluence points quota that transfer to Jira (2026-08-20)",
  "forge-platform-facts/jira-forge/5b7cf75d/rate-limit-handling-in-jira-forge-1": "Rate Limit Handling in Jira Forge",
  "forge-platform-facts/jira-forge/e828b082/bulk-endpoints-need-the-global-bulk-change-permission-7": "Bulk endpoints need the Global bulk change permission",
  "forge-platform-facts/jira-forge/e828b082/custom-ui-modal-sizing-5": "Custom UI modal sizing",
  "forge-platform-facts/jira-forge/e828b082/forge-development-gotchas-jira-1": "Forge Development Gotchas (Jira)",
  "forge-platform-facts/jira-forge/e828b082/kvs-query-has-no-sort-6": "kvs.query() has no sort()",
  "forge-platform-facts/jira-forge/e828b082/no-use-before-define-is-not-a-style-rule-in-a-forge-function-2": "no-use-before-define is not a style rule in a Forge function",
  "forge-platform-facts/jira-forge/e828b082/permissions-external-images-is-separate-from-fetch-3": "permissions.external.images is separate from fetch",
  "forge-platform-facts/jira-forge/e828b082/workflow-validator-error-messages-4": "Workflow validator error messages",
  "forge-platform-facts/platform-fact-memories/93df0223/async-events-queues-and-post-function-timing-3": "Async events, queues and post-function timing",
  "forge-platform-facts/platform-fact-memories/93df0223/automation-the-browser-and-rest-first-8": "Automation, the browser, and REST first",
  "forge-platform-facts/platform-fact-memories/93df0223/custom-ui-jira-expressions-in-the-wild-and-the-route-helper-5": "Custom UI, Jira expressions in the wild, and the route helper",
  "forge-platform-facts/platform-fact-memories/93df0223/forge-llm-contract-and-cost-4": "Forge LLM contract and cost",
  "forge-platform-facts/platform-fact-memories/93df0223/forge-platform-facts-1": "Forge platform facts",
  "forge-platform-facts/platform-fact-memories/93df0223/identity-permissions-and-what-an-endpoint-quietly-excludes-6": "Identity, permissions and what an endpoint quietly excludes",
  "forge-platform-facts/platform-fact-memories/93df0223/service-management-comments-and-visibility-7": "Service management comments and visibility",
  "forge-platform-facts/platform-fact-memories/93df0223/workflow-rules-over-rest-and-the-workflows-api-2": "Workflow rules over REST and the workflows API",
  "jira-rest-correctness/jira-api/86cb78d3/field-writes-can-silently-no-op-editmeta-before-write-2": "Field writes can silently no-op (editmeta before write)",
  "jira-rest-correctness/jira-api/86cb78d3/forge-development-gotchas-jira-1": "Forge Development Gotchas (Jira)",
  "jira-rest-correctness/jira-api/86cb78d3/post-rest-api-3-issue-bulk-returns-only-the-successes-3": "POST /rest/api/3/issue/bulk returns ONLY the successes",
  "jira-rest-correctness/jira-api/ff281fe4/common-problem-patterns-for-jira-forge-1": "Common Problem Patterns for Jira Forge",
  "jira-rest-correctness/jira-api/ff281fe4/configuration-ui-3": "Configuration UI",
  "jira-rest-correctness/jira-api/ff281fe4/detect-and-respond-to-configuration-updates-6": "Detect and Respond to Configuration Updates",
  "jira-rest-correctness/jira-api/ff281fe4/manifest-configuration-2": "Manifest Configuration",
  "jira-rest-correctness/jira-api/ff281fe4/next-steps-8": "Next Steps",
  "jira-rest-correctness/jira-api/ff281fe4/rate-limit-helper-function-4": "Rate Limit Helper Function",
  "jira-rest-correctness/jira-api/ff281fe4/validator-with-multiple-validation-rules-5": "Validator with Multiple Validation Rules",
  "jira-rest-correctness/jira-api/ff281fe4/webhook-style-sync-to-external-system-7": "Webhook-style Sync to External System",
  "jsm-correctness/jira-forge/2aa673c7/auto-assignment-based-on-category-7": "Auto-Assignment Based on Category",
  "jsm-correctness/jira-forge/2aa673c7/auto-resolve-based-on-customer-inactivity-8": "Auto-Resolve Based on Customer Inactivity",
  "jsm-correctness/jira-forge/2aa673c7/custom-email-notifications-via-webhooks-10": "Custom Email Notifications via Webhooks",
  "jsm-correctness/jira-forge/2aa673c7/custom-form-with-validation-part-1-5": "Custom Form with Validation (part 1)",
  "jsm-correctness/jira-forge/2aa673c7/custom-form-with-validation-part-2-6": "Custom Form with Validation (part 2)",
  "jsm-correctness/jira-forge/2aa673c7/jira-service-management-jsm-extensions-with-forge-1": "Jira Service Management (JSM) Extensions with Forge",
  "jsm-correctness/jira-forge/2aa673c7/link-service-requests-to-kb-articles-9": "Link Service Requests to KB Articles",
  "jsm-correctness/jira-forge/2aa673c7/manifest-configuration-for-sla-monitoring-4": "Manifest Configuration for SLA Monitoring",
  "jsm-correctness/jira-forge/2aa673c7/monitor-and-act-on-sla-breaches-3": "Monitor and Act on SLA Breaches",
  "jsm-correctness/jira-forge/2aa673c7/step-2-add-custom-fields-to-request-types-2": "Step 2: Add Custom Fields to Request Types",
  "jsm-correctness/jira-forge/2aa673c7/summary-of-jsm-forge-capabilities-11": "Summary of JSM Forge Capabilities",
  "voice-rules/voice-rules/adf3f44d/affirmationopeners-and-assistanttalk-6": "affirmationOpeners and assistantTalk",
  "voice-rules/voice-rules/adf3f44d/blockrules-4": "blockRules",
  "voice-rules/voice-rules/adf3f44d/claimwords-and-airegisterwords-8": "claimWords and aiRegisterWords",
  "voice-rules/voice-rules/adf3f44d/methodleaks-2": "methodLeaks",
  "voice-rules/voice-rules/adf3f44d/methodleakverbs-and-hedgewords-7": "methodLeakVerbs and hedgeWords",
  "voice-rules/voice-rules/adf3f44d/registerwordcaps-and-defaultregister-3": "registerWordCaps and defaultRegister",
  "voice-rules/voice-rules/adf3f44d/shapethresholds-9": "shapeThresholds",
  "voice-rules/voice-rules/adf3f44d/voice-rules-1": "Voice rules",
  "voice-rules/voice-rules/adf3f44d/warnrules-5": "warnRules"
};

export default KNOWLEDGE_TITLES;
