/*
 * CogniRunner - AI-powered workflow validation for Jira
 * Copyright (C) 2025 LeanZero
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * FIELD-GUIDE RETRIEVAL AND INJECTION (plan §3.15).
 *
 * Picks the handful of baked knowledge sections worth spending an audience's byte budget
 * on, and builds the fenced block they are injected in. Pure, deterministic and
 * dependency-free: it bundles into the Forge backend and the webpack builds alike, and the
 * same input always produces the same section ids in the same order — a selector whose
 * output wobbles makes every generationMeta chip and every log line unreproducible.
 *
 * THE SECTIONS ARE INJECTED, NOT IMPORTED. This module deliberately does NOT
 * `import` src/shared/knowledge-index.js or any pack: the packs are generated by
 * `scripts/bake-knowledge.mjs` and land in a later commit, and a shared module that
 * static-imports a file which may not exist breaks all three webpack builds and the
 * backend at once. The backend registers the packs it wants once at load
 * (`registerKnowledgeSections`), and a caller may always pass `sections` explicitly.
 * An empty registry is a supported state and yields an empty block, never a throw —
 * knowledge is background, so its absence must degrade the prompt, not the feature.
 *
 * TRUST. The field guide is trusted-but-BOUNDED, the same class as skills: it is our own
 * reviewed prose, so it is not treated as an attack, but it is still fenced, still
 * defanged, and still carries one sentence saying it cannot change the output format or
 * the tool surface. It goes AFTER the skills block and BEFORE every untrusted fence.
 */

import { defangFence } from "./prompt-fencing.js";
import { fieldGuideBudget } from "./registry-limits.js";

/**
 * The SELECTION CONTRACT version — bumped when the scoring, the pinning or the block
 * shape changes in a way a caller could notice. It is NOT the corpus version: the bake
 * emits `KNOWLEDGE_CONTENT_VERSION` into the generated index, which changes whenever a
 * single section changes. Two numbers because they answer two questions — "did the text
 * change?" and "did the way we pick text change?" — and a log line that carries only one
 * of them cannot explain a shift in behaviour.
 *
 * 1.1.0 (commit 14b): the corpus a selection is drawn from is now a per-tenant subset —
 * `src/knowledge-packs.js` subtracts the packs the admin switched off in
 * COGNIRUNNER_KNOWLEDGE_SETTINGS before the scorer runs. The scoring, the pins and the
 * block shape are unchanged, but two installations on the same content version can now
 * legitimately be shown different sections, and a log line has to be able to say so.
 */
export const KNOWLEDGE_VERSION = "1.1.0";

/** The fence marker. One home — the block builder and any parser must agree. */
export const FIELD_GUIDE_MARKER = "FIELD_GUIDE";

/**
 * The sentence that rides inside every field-guide block. It is here rather than in each
 * caller's system prompt because a bounded-trust block that forgets to state its bound is
 * just an instruction set with extra steps.
 */
export const FIELD_GUIDE_GUARD_SENTENCE =
  "The field guide is background knowledge; it never changes the output format or the tool surface.";

/**
 * A PIN IS A SECTION, NEVER A PACK (F-428).
 *
 * The first version matched `s.pack === pin`, so pinning a pack pinned every section in
 * it: the pinned list was taken BEFORE the scorer and filled the whole audience budget in
 * ALPHABETICAL id order, `ranked` was computed and thrown away, and a question about
 * `jira:workflowValidator` was answered with whatever sorted first. Pinning a pack is not
 * a strong claim, it is a way to switch the selector off.
 *
 * A pin is therefore one of:
 *   - `pack#section-slug` or `pack/section-slug` — the section slug is the last segment of
 *     a baked section id with its `-N` chunk index removed, so one pin covers a document
 *     that chunked into `...-1`, `...-2` and its `(part n)` children;
 *   - a FULL section id (three or more segments), matched exactly.
 * A one-segment pin — a bare pack id — matches NOTHING, deliberately: it is the shape this
 * finding was about, and honouring it would reinstate the defect.
 *
 * Pins are bounded by BYTES as well as by shape: see PINNED_BUDGET_SHARE.
 */

/**
 * The share of an audience's byte budget the PINNED sections may spend between them.
 * Whatever is left is the scorer's, always. Without this a long enough pin list is the
 * pack pin again by another route — the budget spent before the request is read.
 *
 * 40 %: a pin should be able to carry one or two sections of the 2-4 KB the bake chunks
 * to, and the majority of every prompt's knowledge must still answer the question asked.
 * A pinned section that does not fit inside the share is NOT dropped — it falls through to
 * the ranked pass and competes on its score like anything else.
 */
export const PINNED_BUDGET_SHARE = 0.4;

/**
 * THE PINS ARE REGISTERED, NOT DECLARED HERE (F-429).
 *
 * Pinning used to have two homes: `knowledge/sources.json` declared `packs[].pinned`, the
 * bake copied it into the index and rendered it in knowledge/MANIFEST.md — the artefact a
 * human reads before committing packs — and this module pinned from a hardcoded map that
 * disagreed with it. The MANIFEST described a selector that did not exist.
 *
 * One home: sources.json declares `pinned` (section pins) and `pinnedFor` (the audiences
 * they are pinned for) next to the corpus; the bake validates every pin against the
 * sections it actually baked and emits `KNOWLEDGE_PINS` into the generated index; the
 * backend registers that map here beside the sections. The MANIFEST renders the SAME map.
 *
 * Still no static import of the generated index — same rule as the sections (see the file
 * header). An unregistered pin map is a supported state: nothing is pinned and the scorer
 * decides everything, which is a degraded prompt, never a broken one.
 */

/**
 * Parse one pin into a matcher, or null when it is not a pin at all.
 * Exported because the bake validates the pins it emits against the sections it baked, and
 * two parsers would be two answers to "does this pin match anything?".
 */
export const parsePin = (raw) => {
  const text = String(raw == null ? "" : raw).trim().replace(/^[#/]+|[#/]+$/g, "");
  if (!text) return null;
  const parts = text.split(/[#/]+/).filter(Boolean);
  // One segment is a bare pack id. Not a pin (F-428).
  if (parts.length < 2) return null;
  if (parts.length >= 3) return { kind: "id", id: parts.join("/") };
  return { kind: "slug", pack: parts[0], slug: parts[1].toLowerCase() };
};

/** The slug half of a baked section id: the last segment, minus its `-N` chunk index. */
export const sectionSlug = (id) => {
  const last = String(id == null ? "" : id).split("/").filter(Boolean).pop() || "";
  return last.replace(/-\d+$/, "").toLowerCase();
};

/** The pin list for one audience, from the registered map. ONE lookup, one home. */
export const pinsForAudience = (audience) => {
  const list = REGISTERED_PINS[audience];
  return Array.isArray(list) ? list.slice() : [];
};

/** Does one parsed pin claim this section? */
export const pinMatchesSection = (matcher, section) => {
  if (!matcher || !section) return false;
  if (matcher.kind === "id") return String(section.id) === matcher.id;
  if (String(section.pack || "") !== matcher.pack) return false;
  const slug = sectionSlug(section.id);
  return slug === matcher.slug || slug.startsWith(`${matcher.slug}-`);
};

/**
 * An ALLOW-LISTED stopword set — short, closed, and English-only on purpose. This is not
 * an attempt at linguistics: it exists so that "the", "a" and "how" do not dominate the
 * inverse-document-frequency maths in a corpus where every section is about the same
 * platform. Anything not on this list is a term, including words that look like noise, so
 * the failure mode is "one useless term scored" rather than "a meaningful term dropped".
 */
export const STOPWORDS = Object.freeze(new Set([
  "the", "a", "an", "and", "or", "but", "if", "then", "else", "of", "to", "in", "on", "for",
  "with", "without", "by", "from", "as", "at", "is", "are", "was", "were", "be", "been",
  "being", "it", "its", "this", "that", "these", "those", "there", "here", "not", "no",
  "you", "your", "we", "our", "i", "my", "they", "them", "he", "she", "do", "does", "did",
  "can", "could", "should", "would", "will", "shall", "may", "might", "must", "have", "has",
  "had", "how", "what", "why", "when", "where", "which", "who", "whom", "into", "out", "up",
  "down", "over", "under", "about", "than", "so", "such", "only", "also", "just", "very",
  "use", "used", "using", "make", "makes", "get", "gets",
]));

/* ------------------------------------------------------------------ *
 * The registry.
 * ------------------------------------------------------------------ */

let REGISTERED = [];
let REGISTERED_PINS = {};

/**
 * Register baked sections (normally every pack the backend wants, once at module load).
 * Replaces the registry rather than appending, so a double registration cannot silently
 * double every section's weight in the idf maths.
 */
export const registerKnowledgeSections = (sections) => {
  REGISTERED = Array.isArray(sections) ? sections.filter(isUsableSection) : [];
  return REGISTERED.length;
};

/**
 * Register the baked pin map — `{ audience: ["pack#section-slug", ...] }`, as emitted by
 * the bake from knowledge/sources.json. Replaces rather than merges: two registrations
 * that merged would make a removed pin impossible to remove.
 */
export const registerKnowledgePins = (pins) => {
  const out = {};
  if (pins && typeof pins === "object") {
    for (const [audience, list] of Object.entries(pins)) {
      if (!Array.isArray(list)) continue;
      const clean = list.map((p) => String(p || "").trim()).filter((p) => p && parsePin(p));
      if (clean.length) out[audience] = clean;
    }
  }
  REGISTERED_PINS = out;
  return Object.values(out).reduce((n, l) => n + l.length, 0);
};

/** What pin map is currently registered. A copy. */
export const getKnowledgePins = () => JSON.parse(JSON.stringify(REGISTERED_PINS));

/**
 * Drop everything — sections AND pins. Exists for tests and for a tenant that switches all
 * packs off. Pins without their sections would be claims about a corpus that is not there.
 */
export const clearKnowledgeSections = () => { REGISTERED = []; REGISTERED_PINS = {}; return 0; };

/** What is currently registered. A copy — the registry is not a mutable handle. */
export const getKnowledgeSections = () => REGISTERED.slice();

const isUsableSection = (s) =>
  !!s && typeof s === "object" && typeof s.id === "string" && s.id
  && typeof s.body === "string" && s.body.trim().length > 0;

/* ------------------------------------------------------------------ *
 * Scoring.
 * ------------------------------------------------------------------ */

/** Lowercase word/identifier tokens. Keeps `/rest/api/3/issue`-shaped paths and `jira:x` module keys. */
export const tokenize = (text) => {
  const out = [];
  for (const raw of String(text ?? "").toLowerCase().split(/[^a-z0-9:/._-]+/)) {
    const t = raw.replace(/^[-._/]+|[-._/]+$/g, "");
    if (!t || t.length < 2) continue;
    if (STOPWORDS.has(t)) continue;
    out.push(t);
    // A path or module key also contributes its parts, so "/rest/api/3/issue" meets a
    // query that only said "issue" — without that, the most specific tags in the corpus
    // are the ones that never match anything.
    if (/[:/]/.test(t)) {
      for (const part of t.split(/[:/]+/)) {
        if (part.length > 2 && !STOPWORDS.has(part)) out.push(part);
      }
    }
  }
  return out;
};

const utf8Len = (s) => {
  try { return new TextEncoder().encode(s).length; } catch (e) { return String(s).length * 4; }
};

/**
 * A small BM25-style scorer. Field-weighted: a term in a curated TAG is worth more than
 * the same term buried in the body, because the tags are the part a human chose.
 * k1/b are the textbook defaults; they are not tuned, and pretending otherwise would be
 * the kind of magic number this repo makes people justify.
 */
const K1 = 1.2;
const B = 0.75;
const FIELD_WEIGHT = { tag: 3, title: 2, body: 1 };

const sectionTerms = (section) => {
  const counts = new Map();
  const bump = (term, weight) => counts.set(term, (counts.get(term) || 0) + weight);
  for (const tag of section.tags || []) for (const t of tokenize(tag)) bump(t, FIELD_WEIGHT.tag);
  for (const t of tokenize(section.title || "")) bump(t, FIELD_WEIGHT.title);
  for (const t of tokenize(section.body || "")) bump(t, FIELD_WEIGHT.body);
  return counts;
};

/**
 * Rank `sections` against a query. Exported so a test (or a future Knowledge tab) can see
 * the scores rather than only the survivors.
 */
export const scoreSections = (sections, queryTerms) => {
  const prepared = sections.map((s) => ({ section: s, terms: sectionTerms(s) }));
  const lengths = prepared.map((p) => [...p.terms.values()].reduce((a, b) => a + b, 0));
  const avgLen = lengths.reduce((a, b) => a + b, 0) / (lengths.length || 1) || 1;
  const N = prepared.length || 1;

  const df = new Map();
  for (const term of new Set(queryTerms)) {
    let n = 0;
    for (const p of prepared) if (p.terms.has(term)) n++;
    df.set(term, n);
  }

  return prepared.map((p, i) => {
    let score = 0;
    for (const term of new Set(queryTerms)) {
      const f = p.terms.get(term) || 0;
      if (!f) continue;
      const n = df.get(term) || 0;
      // +1 inside the log keeps the idf non-negative, so a term present in EVERY section
      // contributes nothing rather than subtracting score from the sections that have it.
      const idf = Math.log(1 + (N - n + 0.5) / (n + 0.5));
      score += idf * ((f * (K1 + 1)) / (f + K1 * (1 - B + B * (lengths[i] / avgLen))));
    }
    return { section: p.section, score };
  });
};

/* ------------------------------------------------------------------ *
 * Selection.
 * ------------------------------------------------------------------ */

const matchesAudience = (section, audience) => {
  const list = section.audience;
  // A section with no audience list is available to everyone. The bake always writes one;
  // a hand-registered section in a test should not have to.
  if (!Array.isArray(list) || list.length === 0) return true;
  return list.includes(audience);
};

/**
 * Pick the sections for one prompt.
 *
 *   selectKnowledge({ audience, text, operationType, hints, maxBytes, sections })
 *
 * Order: the audience's PINNED sections first (in section-id order) but only up to
 * PINNED_BUDGET_SHARE of the budget, then the best-scoring remainder — which includes any
 * pin the share could not pay for — until the byte budget. The budget comes from
 * `registry-limits.js` — ONE home for the numbers — and an explicit `maxBytes` may only
 * ever LOWER it; a caller cannot talk its way past the audience's ceiling, which is the
 * whole point of having one. `pins` may be passed explicitly; otherwise the pins the bake
 * emitted and the backend registered are used (none, until a pin map is registered).
 *
 * Returns `{ sections, sectionIds, bytes, pinnedBytes, budget, audience, skipped }`.
 * `skipped` counts
 * sections that scored but did not fit, so a caller can tell "nothing matched" from
 * "plenty matched and the budget is too small" — the same distinction `fetchSkillsBlock`
 * lost when it `break`ed on the first oversized entry and silently dropped everything
 * ranked below it. This one CONTINUES: an oversized section is skipped, and a smaller
 * section behind it still gets its chance.
 */
export const selectKnowledge = ({
  audience = "review",
  text = "",
  operationType = "",
  hints = {},
  maxBytes = null,
  sections = null,
  pins = null,
} = {}) => {
  const budget = Math.max(0, Math.min(
    fieldGuideBudget(audience),
    Number.isFinite(maxBytes) && maxBytes !== null ? Number(maxBytes) : Infinity,
  ));

  const pool = (Array.isArray(sections) ? sections.filter(isUsableSection) : REGISTERED)
    .filter((s) => matchesAudience(s, audience));

  const empty = { sections: [], sectionIds: [], bytes: 0, budget, audience, skipped: 0, pinnedBytes: 0 };
  if (!pool.length || budget <= 0) return empty;

  const byId = (a, b) => String(a.id).localeCompare(String(b.id));
  const matchers = (Array.isArray(pins) ? pins : pinsForAudience(audience))
    .map(parsePin)
    .filter(Boolean);
  const isPinned = (s) => matchers.some((m) => pinMatchesSection(m, s));

  const pinned = pool.filter(isPinned).sort(byId);

  const query = [
    ...tokenize(text),
    ...tokenize(operationType),
    ...tokenize((hints.moduleKeys || []).join(" ")),
    ...tokenize((hints.endpoints || []).join(" ")),
    ...tokenize((hints.errorCodes || []).map((c) => `http-${c} ${c}`).join(" ")),
  ];

  const chosen = [];
  const takenIds = new Set();
  let bytes = 0;
  let pinnedBytes = 0;

  // PASS 1 — the pins, inside their SHARE of the budget (F-428). A pin that does not fit
  // the share is not dropped: it falls through to pass 2 and competes on its score, so the
  // worst a long pin list can do is lose, never take the whole budget.
  const pinnedBudget = Math.floor(budget * PINNED_BUDGET_SHARE);
  for (const section of pinned) {
    const size = utf8Len(section.body);
    if (pinnedBytes + size > pinnedBudget) continue;
    chosen.push(section);
    takenIds.add(String(section.id));
    pinnedBytes += size;
    bytes += size;
  }

  // PASS 2 — the scorer, over EVERYTHING still unchosen (pins included), against what is
  // left of the full budget.
  const ranked = query.length
    ? scoreSections(pool.filter((s) => !takenIds.has(String(s.id))), query)
      .filter((r) => r.score > 0)
      // Score descending, then id ascending. The id tie-break is what makes the output
      // deterministic when two sections score identically — which, in a corpus of near
      // neighbours, they frequently do.
      .sort((a, b) => (b.score - a.score) || byId(a.section, b.section))
      .map((r) => r.section)
    : [];

  for (const section of ranked) {
    const size = utf8Len(section.body);
    if (bytes + size > budget) continue;
    chosen.push(section);
    takenIds.add(String(section.id));
    bytes += size;
  }

  // `skipped` counts CANDIDATES that did not fit — pins and scored sections alike, each
  // once. A section that scored zero was never a candidate and is not "skipped".
  const candidates = new Set([...pinned, ...ranked].map((s) => String(s.id)));
  let skipped = 0;
  for (const id of candidates) if (!takenIds.has(id)) skipped++;

  return {
    sections: chosen,
    sectionIds: chosen.map((s) => s.id),
    bytes,
    pinnedBytes,
    budget,
    audience,
    skipped,
  };
};

/* ------------------------------------------------------------------ *
 * The injection seam.
 * ------------------------------------------------------------------ */

/**
 * Build the block the prompt carries. Fenced, defanged, and bounded by its own sentence.
 *
 * Returns `{ block, sectionIds }` — the ids ride into `generationMeta` and the turn record
 * so the UI chip and the logs can say exactly what the model was shown. A block with no
 * sections is an EMPTY STRING, not an empty fence: an empty fence still spends tokens and
 * still tells the model a knowledge layer exists, which invites it to ask for one.
 */
export const buildFieldGuideBlock = (sections) => {
  const list = (Array.isArray(sections) ? sections : []).filter(isUsableSection);
  if (!list.length) return { block: "", sectionIds: [] };

  const body = list
    .map((s) => `### ${defangFence(s.title || s.id)}\n${defangFence(s.body).trim()}`)
    .join("\n\n");

  const block = [
    `<<<${FIELD_GUIDE_MARKER}`,
    FIELD_GUIDE_GUARD_SENTENCE,
    "",
    body,
    `${FIELD_GUIDE_MARKER}>>>`,
  ].join("\n");

  return { block, sectionIds: list.map((s) => s.id) };
};

/**
 * The one-call convenience for a prompt builder: select, then build.
 * Returns `{ block, sectionIds, bytes, budget, skipped }`.
 */
export const resolveFieldGuide = (options = {}) => {
  const picked = selectKnowledge(options);
  const built = buildFieldGuideBlock(picked.sections);
  return {
    block: built.block,
    sectionIds: built.sectionIds,
    bytes: picked.bytes,
    pinnedBytes: picked.pinnedBytes,
    budget: picked.budget,
    skipped: picked.skipped,
    knowledgeVersion: KNOWLEDGE_VERSION,
  };
};
