/* CogniRunner - Copyright (C) 2025 LeanZero. SPDX-License-Identifier: AGPL-3.0-or-later */
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from '../../static/_screenshot-harness/node_modules/playwright/index.mjs';
import {JIRA_EVENTS} from '../../src/shared/jira-events.js';
import {AGENT_ACTIONS} from '../../src/shared/agent-actions.js';
const out=process.env.PROOF_OUT||new URL('../results/listeners-jobs-campaign/ui-final/',import.meta.url).pathname, state=JSON.parse(fs.readFileSync(new URL('../results/listeners-jobs-campaign/state.json',import.meta.url)));
fs.mkdirSync(out,{recursive:true});
const evidence={startedAt:new Date().toISOString(),records:[],checks:[],errors:[],console:[],screenshots:[]};
const flush=()=>fs.writeFileSync(out+'/evidence.json',JSON.stringify(evidence,null,2));
function check(key,a,b){let pass=true;try{assert.deepEqual(a,b);}catch{pass=false;}evidence.checks.push({key,pass,...(!pass?{actual:a,expected:b}:{})});if(!pass)console.log('MISMATCH',key,JSON.stringify(a),JSON.stringify(b));}
const browser=await chromium.launch({headless:true});const ctx=await browser.newContext({storageState:'/Users/mihaiperdum/Projects/forge-live-harness/.auth/storage-state.json',viewport:{width:1440,height:1100}});const page=await ctx.newPage();const frame=page.frameLocator('iframe').first();
page.on('console',m=>{if(m.type()==='error')evidence.console.push({type:m.type(),text:m.text()});});page.on('pageerror',e=>evidence.console.push({type:'pageerror',text:e.message}));
function waitInvoke(name,id){return page.waitForResponse(r=>{const p=r.request().postData()||'';return p.includes('"'+name+'"')&&(!id||p.includes(id));},{timeout:45000});}
async function extract(){return frame.locator('.lst-editor').evaluate(e=>{const text=n=>n?.textContent.trim()||'';return {name:e.querySelector('#lst-name,#job-name')?.value,description:e.querySelector('#lst-desc,#job-desc')?.value,events:[...e.querySelectorAll('.evp-selected button')].map(n=>n.getAttribute('aria-label').replace(/^Remove /,'')),filters:[...e.querySelectorAll('.lst-filter')].map(n=>({label:text(n.querySelector('.lst-filter-label')),chips:[...n.querySelectorAll('.chips-x')].map(x=>x.getAttribute('aria-label').replace(/^Remove /,'')),value:n.querySelector('input.lst-input')?.value})),aiCondition:e.querySelector('#lst-aicond')?.value,ignoreSelf:[...e.querySelectorAll('.lst-check')].find(n=>text(n).includes('Ignore events caused'))?.querySelector('input').checked,mode:[...e.querySelectorAll('[role=radio]')].filter(n=>n.getAttribute('aria-checked')==='true').map(n=>text(n.querySelector('.mode-btn-title'))),options:[...e.querySelectorAll('.lst-options .lst-check')].map(n=>({label:text(n.querySelector('strong')),checked:n.querySelector('input').checked})),functions:[...e.querySelectorAll('.function-block')].map(n=>({name:n.querySelector('.function-name-input')?.value,prompt:[...n.querySelectorAll('.form-group')].find(g=>text(g.querySelector('.label')).startsWith('What should this step do?'))?.querySelector('textarea')?.value,checkboxes:[...n.querySelectorAll('input[type=checkbox]')].map(i=>({checked:i.checked,label:i.closest('label')?.textContent.trim()})),code:[...n.querySelectorAll('.cm-line')].map(l=>l.textContent).join('\n'),groups:[...n.querySelectorAll('.form-group')].map(g=>({label:text(g.querySelector('.label')),inputs:[...g.querySelectorAll('input,textarea')].map(i=>({type:i.type,value:i.value,checked:i.checked})),selected:[...g.querySelectorAll('.dropdown-trigger')].map(text)}))})),agent:{instructions:e.querySelector('#agc-instructions')?.value,maxRounds:e.querySelector('#agc-rounds')?.value,actions:[...e.querySelectorAll('.agc-action')].map(n=>({label:text(n.querySelector('.agc-action-label')),checked:n.querySelector('input').checked}))},schedule:{cron:text(e.querySelector('.schp-preview-cron')),zone:text(e.querySelector('[aria-label="Time zone"]')),preset:text(e.querySelector('[aria-label="Schedule preset"]')),preview:text(e.querySelector('.schp-preview')),times:[...e.querySelectorAll('.schp-preview-run')].map(text)},scope:{jql:e.querySelector('.job-scope > input')?.value,maxIssues:e.querySelector('.job-scope-max input')?.value},bodyWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,overflow:[...e.querySelectorAll('input,button,.cm-editor,.agc-actions,.lst-filters,.job-scope')].map(n=>({tag:n.tagName,cls:n.className,rect:n.getBoundingClientRect().toJSON()})).filter(n=>n.rect.right>document.documentElement.clientWidth+2||n.rect.left< -2)};});}
try{await page.goto('https://wolfaenpak.atlassian.net/jira/apps/36415848-6868-4697-9554-3c3ad87b8da9/989ecaa0-261b-406e-b444-78c01c0d7772',{waitUntil:'domcontentloaded'});await frame.locator('.tab-btn').filter({hasText:/^Listeners$/}).waitFor({timeout:60000});
for(const width of [1440,1024])for(const theme of ['light','dark']){
await page.setViewportSize({width,height:1100});await frame.locator('html').evaluate((e,t)=>{e.setAttribute('data-color-mode',t);e.setAttribute('data-theme',`${t}:${t}`);},theme);
for(const [kind,tab]of [['listeners','Listeners'],['jobs','Scheduled Jobs']]){
await frame.locator('.tab-btn').filter({hasText:new RegExp('^'+tab+'$')}).click();await frame.getByRole('textbox',{name:kind==='listeners'?'Search listeners':'Search jobs',exact:true}).fill(state.tag);
await frame.locator('.lst-name').filter({hasText:state[kind][0].name}).waitFor({timeout:30000});
check(`${width}/${theme}/${kind}/row-count`,await frame.locator('.lst-name').count(),state[kind].length);
await page.screenshot({path:`${out}/${width}-${theme}-${kind}-list.png`,fullPage:true});
for(const item of state[kind]){const key=`${width}/${theme}/${item.code}`;let record={key,code:item.code,id:item.id,width,theme};evidence.records.push(record);
try{const name=frame.locator('.lst-name').filter({hasText:new RegExp('^'+state.tag+' '+item.code+' ')});const row=name.locator('..').locator('..');await row.waitFor({timeout:20000});record.list={text:await row.innerText(),mode:await row.locator('.type-badge').innerText(),scope:await row.locator('.lst-scope').innerText(),stats:await row.locator('.runstat').innerText(),statsClass:await row.locator('.runstat').getAttribute('class'),statsTitle:await row.locator('.runstat').getAttribute('title'),disabled:await row.locator('.status-disabled').count(),simulation:await row.locator('.lst-sim').count(),gate:await row.locator('.lst-aic').count(),geometry:await row.evaluate(e=>({right:e.getBoundingClientRect().right,width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}))};
const response=waitInvoke(kind==='listeners'?'getListener':'getScheduledJob',item.id);await row.getByRole('button',{name:'Edit',exact:true}).click();const r=await response;const body=(await r.json()).data?.invokeExtension?.response?.body;const c=body?.listener||body?.job;if(!c)throw Error('missing full resolver config '+JSON.stringify(body));record.config=c;await frame.locator(kind==='listeners'?'#lst-name':'#job-name').waitFor({timeout:30000});record.ui=await extract();const u=record.ui;
check(key+'/id',c.id,item.id);check(key+'/name',u.name,c.name);check(key+'/description',u.description,c.description);check(key+'/mode',u.mode,[c.mode==='agent'?'AI agent':'Code steps']);check(key+'/list-mode',record.list.mode,c.mode==='agent'?'AI AGENT':'CODE');check(key+'/list-disabled',record.list.disabled,c.enabled===false?1:0);check(key+'/list-simulation',record.list.simulation,c.simulationMode?1:0);for(const [label,field]of [['Simulation mode','simulationMode'],['Suppress notifications','suppressNotifications'],['Enabled','enabled']])check(key+'/'+field,u.options.find(x=>x.label===label)?.checked,!!c[field]);
if(kind==='listeners'){check(key+'/events',u.events,c.events.map(id=>JIRA_EVENTS.find(e=>e.id===id)?.label||id));check(key+'/aiCondition',u.aiCondition,c.aiCondition);check(key+'/ignoreSelf',u.ignoreSelf,c.ignoreSelf!==false);check(key+'/scope-list',record.list.scope,c.filters.projectKeys.join(', ')||'All projects');check(key+'/list-ai-gate',record.list.gate,c.aiCondition?1:0);for(const [label,field]of [['Projects','projectKeys'],['Issue types','issueTypes'],['Changed fields','changedFields'],['Comment matches (regex)','commentPattern'],['Issue matches JQL','jql']]){const f=u.filters.find(x=>x.label===label);if(f)check(key+'/filter-'+field,Array.isArray(c.filters[field])?f.chips:f.value,c.filters[field]);else if(c.filters[field]?.length)check(key+'/filter-visible-'+field,false,true);}}
else{check(key+'/cron',u.schedule.cron,c.schedule.cron);check(key+'/zone',u.schedule.zone,c.schedule.timeZone);check(key+'/scope-jql',u.scope.jql,c.scope?.jql||'');if(c.scope)check(key+'/scope-max',Number(u.scope.maxIssues),c.scope.maxIssues);check(key+'/scope-list',record.list.scope,c.scope?.jql?'Per JQL issue':'Once');check(key+'/preview-5',u.schedule.times.length,5);}
if(c.mode==='agent'){check(key+'/agent-instructions',u.agent.instructions,c.agent.instructions);check(key+'/agent-maxrounds',Number(u.agent.maxRounds),c.agent.maxRounds);check(key+'/agent-actions',u.agent.actions,AGENT_ACTIONS.filter(a=>a.kind==='read'||a.kind==='write').sort((a,b)=>(a.kind==='read'?0:1)-(b.kind==='read'?0:1)).map(a=>({label:a.label,checked:c.agent.allowedActions.includes(a.id)})));}
else{check(key+'/step-count',u.functions.length,c.functions.length);for(let i=0;i<c.functions.length;i++){check(key+'/step'+i+'name',u.functions[i]?.name,c.functions[i].name);check(key+'/step'+i+'prompt',u.functions[i]?.prompt,c.functions[i].operationPrompt);check(key+'/step'+i+'code',u.functions[i]?.code,c.functions[i].code);const v=u.functions[i]?.groups.find(g=>g.label.startsWith('Result Variable'));if(v)check(key+'/step'+i+'variable',v.inputs[0]?.value,c.functions[i].variableName);}}
check(key+'/theme',await frame.locator('html').getAttribute('data-color-mode'),theme);
await frame.locator('.lst-editor').screenshot({path:`${out}/${key.replaceAll('/','-')}-editor.png`});
record.completedAt=new Date().toISOString();console.log('INSPECTED',key,'checks',evidence.checks.length,'fail',evidence.checks.filter(c=>!c.pass).length);
await frame.getByRole('button',{name:kind==='listeners'?'← Back to listeners':'← Back to jobs',exact:true}).click();await frame.getByRole('textbox',{name:kind==='listeners'?'Search listeners':'Search jobs',exact:true}).fill(state.tag);
}catch(e){record.error=e.stack;evidence.errors.push({key,error:e.stack});console.log('ERROR',key,e.message);await page.screenshot({path:out+'/failure-'+item.code+'.png',fullPage:true});throw e;}finally{flush();}}
}}
}catch(e){evidence.fatal=e.stack;process.exitCode=1;}finally{evidence.finishedAt=new Date().toISOString();flush();await browser.close();console.log('DONE',evidence.records.length,'records',evidence.checks.filter(c=>!c.pass).length,'mismatches',evidence.errors.length,'errors');}

assert.equal(evidence.records.length,128); assert.deepEqual(evidence.errors,[]); assert.equal(evidence.checks.filter(c=>!c.pass).length,0);
