/* CogniRunner - Copyright (C) 2025 LeanZero. SPDX-License-Identifier: AGPL-3.0-or-later */
import fs from 'node:fs';import assert from 'node:assert/strict';
import {testState} from '../lib/rules-api.mjs';
import {getMyself,get,getIssue,post,del,BASE} from '../lib/jira.mjs';
assert.equal(new URL(BASE).hostname,'wolfaenpak.atlassian.net');
const out=new URL('../results/review-proof',import.meta.url).pathname;fs.mkdirSync(out,{recursive:true});const tag=Date.now().toString(36),evidence={tag,checks:[],cleanup:[]};const owned={listeners:[],jobs:[],issues:[]};const me=await getMyself();
const call=async(name,payload={})=>{const r=await testState.post({action:'invokeResolver',functionKey:name,accountId:me.accountId,payload});assert.ok(r.ok,JSON.stringify(r));assert.notEqual(r.body.success,false,JSON.stringify(r.body));return r.body;};
const commentText=c=>JSON.stringify(c.body);let key;
const read=async witness=>{const r=await get(`/rest/api/3/issue/${key}/comment?maxResults=100`);return r.comments.filter(c=>commentText(c).includes(witness));};
const probe=async(name,payload,witness,expected)=>{const before=await read(witness);const r=await testState.post({action:'probeRuleDelivery',...payload});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.directConsumerProbe,true);const after=await read(witness);assert.equal(after.length,expected,name+' count');evidence.checks.push({name,payload,result:r.body,beforeIds:before.map(c=>c.id),after});fs.writeFileSync(out+'/claims-live.json',JSON.stringify(evidence,null,2));console.log('PASS',name,'comments',after.length);return r.body;};
try{
const types=await get('/rest/api/3/issue/createmeta/LZPT/issuetypes?maxResults=100');const type=(types.issueTypes||types.values).find(t=>!t.subtask&&/task/i.test(t.name))||(types.issueTypes||types.values).find(t=>!t.subtask);const issue=await post('/rest/api/3/issue',{fields:{project:{key:'LZPT'},issuetype:{id:type.id},summary:'[Harness claim] '+tag}});key=issue.key;owned.issues.push(key);assert.equal((await getIssue(key,['summary'])).key,key);
const listenerWitness='claim-listener-'+tag;const lst=(await call('saveListener',{listener:{name:'[Harness claim] listener '+tag,enabled:true,events:['avi:jira:created:issue'],filters:{projectKeys:['LZPT'],jql:`key = ${key}`},functions:[{id:'fn1',name:'Comment witness',code:`await api.addComment('${listenerWitness}');`}]}})).listener;owned.listeners.push(lst.id);
const lp={taskType:'listener',ruleId:lst.id,taskId:'harness-claim-l-'+tag,issueKey:key};
let r=await probe('listener concurrent duplicate',lp,listenerWitness,1);assert.equal(r.results.filter(v=>v.skipped&&v.reason==='duplicate delivery').length,1);await probe('listener sequential replay',lp,listenerWitness,1);
const jobWitness='claim-job-'+tag;const job=(await call('saveScheduledJob',{job:{name:'[Harness claim] job '+tag,enabled:true,schedule:{cron:'0 0 1 1 *',timeZone:'UTC'},functions:[{id:'fn1',name:'Comment witness',code:`await api.forIssue('${key}').addComment('${jobWitness}');`}]}})).job;owned.jobs.push(job.id);
const mp={taskType:'scheduledjob',ruleId:job.id,taskId:'harness-claim-m-'+tag,manual:true};r=await probe('manual concurrent duplicate',mp,jobWitness,1);assert.equal(r.results.filter(v=>v.skipped&&v.reason==='duplicate delivery').length,1);await probe('manual sequential replay',mp,jobWitness,1);
const distinct={...mp,taskId:'harness-claim-d1-'+tag,secondTaskId:'harness-claim-d2-'+tag};r=await probe('distinct manual task IDs',distinct,jobWitness,3);assert.equal(r.results.filter(v=>v.skipped).length,0);await probe('distinct manual replay',distinct,jobWitness,3);
const due=new Date();due.setUTCSeconds(0,0);const sp={taskType:'scheduledjob',ruleId:job.id,taskId:'harness-claim-s1-'+tag,secondTaskId:'harness-claim-s2-'+tag,manual:false,scheduledFor:due.toISOString()};r=await probe('same scheduled minute distinct IDs',sp,jobWitness,4);assert.equal(r.results.filter(v=>v.skipped&&v.reason==='duplicate delivery').length,1);await probe('same minute sequential replay',sp,jobWitness,4);
evidence.claims=[];const safe=s=>s.replace(/[^a-zA-Z0-9:._#-]/g,'-').slice(0,120);for(const k of ['lst_exec:'+lp.taskId,'job_exec:'+safe(job.id+':manual:'+mp.taskId),'job_exec:'+safe(job.id+':manual:'+distinct.taskId),'job_exec:'+safe(job.id+':manual:'+distinct.secondTaskId),'job_exec:'+safe(job.id+':'+sp.scheduledFor)]){const r=await testState.get('kvs','&key='+encodeURIComponent(k));assert.ok(r.body.value?.at);evidence.claims.push(r.body);}evidence.pass=true;
}catch(e){evidence.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{
for(const id of owned.listeners){try{await call('deleteListener',{id});assert.ok(!(await call('getListeners')).listeners.some(x=>x.id===id));evidence.cleanup.push({listener:id,removed:true});}catch(e){evidence.cleanup.push({id,error:e.message});process.exitCode=1;}}
for(const id of owned.jobs){try{await call('deleteScheduledJob',{id});assert.ok(!(await call('getScheduledJobs')).jobs.some(x=>x.id===id));evidence.cleanup.push({job:id,removed:true});}catch(e){evidence.cleanup.push({id,error:e.message});process.exitCode=1;}}
for(const key of owned.issues){try{await del('/rest/api/3/issue/'+key);try{await getIssue(key,['summary']);throw Error('issue still exists');}catch(e){assert.equal(e.status,404);}evidence.cleanup.push({issue:key,removed:true});}catch(e){evidence.cleanup.push({key,error:e.message});process.exitCode=1;}}
fs.writeFileSync(out+'/claims-live.json',JSON.stringify(evidence,null,2));console.log('Evidence',out+'/claims-live.json');}
